# Generated by Django 5.1.3 on 2024-11-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='svg',
            field=models.TextField(default='0'),
            preserve_default=False,
        ),
    ]
