# Generated by Django 5.1.3 on 2024-11-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_machines'),
    ]

    operations = [
        migrations.AddField(
            model_name='machines',
            name='corx',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='machines',
            name='cory',
            field=models.TextField(default='0'),
        ),
    ]
