# Generated by Django 5.1.3 on 2024-11-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_machines_corx_machines_cory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='corx',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='machines',
            name='cory',
            field=models.FloatField(default='0'),
        ),
    ]
